runtime: java17
instance_class: F2

env_variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/finance"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: src/main/resources/static

- url: /.*
  script: auto
